Check pipeline status

diff --git a/.github/workflows/pr_to_main.yml b/.github/workflows/pr_to_main.yml
--- a/.github/workflows/pr_to_main.yml
+++ b/.github/workflows/pr_to_main.yml
@@ -62,3 +62,23 @@ jobs:
         uses: codecov/codecov-action@v3
         env:
           CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
+  after:
+    name: After CI/CD
+    runs-on: ubuntu-latest
+    if: ${{ always() }}
+    needs:
+      - setup
+      - ci_tests
+    steps:
+      - name: Check pipeline status
+        run: |
+          echo "setup = ${{ needs.setup.result }}"
+          echo "test_agents = ${{ needs.ci_tests.result }}"
+          if [ "${{ needs.setup.result }}" == "success" ] && \
+              [ "${{ needs.ci_tests.result }}" == "success" ]
+          then
+            echo "Pipeline passed! hooray!!"
+          else
+            echo "Pipeline failed, check the logs on other steps please."
+            exit 1
+          fi
