ACP-0001 Setup GitHub action (#1)

diff --git a/.github/workflows/pr_to_main.yml b/.github/workflows/pr_to_main.yml
--- a/.github/workflows/pr_to_main.yml
+++ b/.github/workflows/pr_to_main.yml
@@ -1,47 +1,84 @@
 name: PR to Main
 on:
-  workflow_dispatch
-  # push:
-  #   branches:
-  #     - main
-  # pull_request:
-  #   branches:
-  #     - main
+  push:
+    branches:
+      - main
+  pull_request:
+    branches:
+      - main
 jobs:
   setup:
     name: Setup CI/CD
     runs-on: ubuntu-latest
     steps:
+      # https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
       - name: Checkout
         uses: actions/checkout@v3
         with:
-          # The branch, tag or SHA to checkout. When checking out the repository that
-          # triggered a workflow, this defaults to the reference or SHA for that event.
-          # Otherwise, uses the default branch.
           ref: ${{ github.event.pull_request.head.sha }}
+          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
           fetch-depth: 0
+
+      # Install project dependencies
       - name: Install Dependencies
         uses: ./.github/actions/install_deps
-      # - uses: nrwl/nx-set-shas@v3
-      # - run: npx nx format:check
-      # - run: npx nx affected -t lint --parallel=3
-      # - run: npx nx affected -t test --parallel=3 --configuration=ci
-      # - run: npx nx affected -t build --parallel=3
+
+      # Print out affected projects and set the output for other jobs to use
+      - name: Derive appropriate SHAs for base and head for `nx affected` commands
+        uses: nrwl/nx-set-shas@v3
+      - name: Get NX Affected projects
+        id: nx-affected
+        run: |
+          nx_affected=$(npx nx show projects --with-target test --affected --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }})
+          echo "nx_affected=$nx_affected" >> $GITHUB_OUTPUT
+      - run: echo "nx_affected=${{ steps.nx-affected.outputs.nx_affected }}"
   ci_tests:
     name: CI Tests
     needs: setup
     runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        action: ['lint', 'format:check', 'test']
     steps:
       - name: Checkout
         uses: actions/checkout@v3
         with:
           ref: ${{ github.event.pull_request.head.sha }}
+          fetch-depth: 0
+
+      - name: Derive appropriate SHAs for base and head for `nx affected` commands
+        uses: nrwl/nx-set-shas@v3
+
       - name: Install Dependencies
         uses: ./.github/actions/install_deps
-      - uses: nrwl/nx-set-shas@v3
-      - name: Run CI Tests
-        run: npx nx affected -t lint format:check test --parallel=3 --configuration=ci
-  # deploy:
-  #   name: Deploy to Non-Prod
-  #   needs: setup
-  #   runs-on: ubuntu-latest
+
+      - name: Tests - ${{ matrix.action }}
+        run: |
+          npx nx affected -t ${{ matrix.action }} --parallel=3 --configuration=ci
+
+      - name: Upload coverage reports to Codecov
+        if: matrix.action == 'test'
+        uses: codecov/codecov-action@v3
+        env:
+          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
+  after:
+    name: After CI/CD
+    runs-on: ubuntu-latest
+    if: ${{ always() }}
+    needs:
+      - setup
+      - ci_tests
+    steps:
+      - name: Check pipeline status
+        run: |
+          echo "setup = ${{ needs.setup.result }}"
+          echo "test_agents = ${{ needs.ci_tests.result }}"
+          if [ "${{ needs.setup.result }}" == "success" ] && \
+              [ "${{ needs.ci_tests.result }}" == "success" ]
+          then
+            echo "Pipeline passed! hooray!!"
+          else
+            echo "Pipeline failed, check the logs on other steps please."
+            exit 1
+          fi
